### ISSUE TITLE
Incorrect file name of freezing_rain_drizzle.svg

### ISSUE THREAD

**Issue by drmrbrewer** [ClimaCell-API/weather-code-icons#1]
I think that `freezing_rain_drizzle.svg` should be renamed to `freezing_drizzle.svg`?  I've seen a `weather_code` value of `freezing_drizzle` returned in my data (with no matching symbol from this icon set)... don't think that `freezing_rain_drizzle` exists as a valid `weather_code` so I reckon that `freezing_rain_drizzle.svg` is the one to use for `freezing_drizzle`?  See what is documented [here](https://docs.developer.climacell.co/docs/weather-codes).

**Comment by LironRS** [comment]
Hi there! The name was changed according to your recommendation. Thank you for reporting this :)
